In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.linear_model import Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

In [2]:
data = pd.read_csv('energydata_complete.csv')

In [3]:
data.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

### 1. From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the R^2 value in two d.p.?

In [5]:
data.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [6]:
y = np.asanyarray(data['T6'])
y = y.reshape(-1, 1)

In [7]:
x = np.asanyarray(data['T2'])
x = x.reshape(-1, 1)

In [8]:
#splitting the data into a train test split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([[ 2.15578912],
       [10.01116055],
       [ 1.87391554],
       ...,
       [ 4.24758774],
       [ 8.69822311],
       [ 4.9893603 ]])

In [27]:
#R squared
r2_score = r2_score(y_test, y_pred)
round(r2_score, 2)

0.64

### Normalize the dataset using the MinMaxScaler after removing the following columns: [“date”, “lights”]. The target variable is “Appliances”. Use a 70-30 train-test set split with a random state of 42 (for reproducibility). Run a multiple linear regression using the training set and evaluate your model on the test set. Answer the following questions:

What is the Mean Absolute Error (in two decimal places)?

In [11]:
data.drop(columns=['date', 'lights'], inplace=True)

In [12]:
scaler = MinMaxScaler()

In [13]:
normalized_df = scaler.fit_transform(data)
normalized_df
# new_data = pd.DataFrame(normalized_df, columns = data.columns)

array([[0.04672897, 0.32734952, 0.56618659, ..., 0.53846154, 0.26544891,
        0.26544891],
       [0.04672897, 0.32734952, 0.54132648, ..., 0.53393665, 0.37208289,
        0.37208289],
       [0.03738318, 0.32734952, 0.53050179, ..., 0.52941176, 0.57284766,
        0.57284766],
       ...,
       [0.24299065, 0.91974657, 0.53866618, ..., 0.89894419, 0.58397859,
        0.58397859],
       [0.38317757, 0.91974657, 0.54949087, ..., 0.8974359 , 0.12637146,
        0.12637146],
       [0.39252336, 0.91974657, 0.53875791, ..., 0.8959276 , 0.68239057,
        0.68239057]])

In [16]:
new_data = pd.DataFrame(normalized_df, columns = data.columns)
new_data

Appliances        T1      RH_1        T2      RH_2        T3      RH_3  \
0        0.046729  0.327350  0.566187  0.225345  0.684038  0.215188  0.746066   
1        0.046729  0.327350  0.541326  0.225345  0.682140  0.215188  0.748871   
2        0.037383  0.327350  0.530502  0.225345  0.679445  0.215188  0.755569   
3        0.037383  0.327350  0.524080  0.225345  0.678414  0.215188  0.758685   
4        0.046729  0.327350  0.531419  0.225345  0.676727  0.215188  0.758685   
...           ...       ...       ...       ...       ...       ...       ...   
19730    0.084112  0.926786  0.537657  0.711655  0.606309  0.830841  0.579374   
19731    0.074766  0.919747  0.536006  0.701769  0.607836  0.825302  0.582178   
19732    0.242991  0.919747  0.538666  0.692651  0.627198  0.818378  0.603988   
19733    0.383178  0.919747  0.549491  0.677054  0.634717  0.805085  0.585294   
19734    0.392523  0.919747  0.538758  0.666171  0.632902  0.799546  0.579062   

             T4      RH_4        T5  ...        T9      RH_9     T_out  \
0      0.351351  0.764262  0.175506  ...  0.223032  0.677290  0.372990   
1      0.351351  0.782437  0.175506  ...  0.226500  0.678532  0.369239   
2      0.344745  0.778062  0.175506  ...  0.219563  0.676049  0.365488   
3      0.341441  0.770949  0.175506  ...  0.219563  0.671909  0.361736   
4      0.341441  0.762697  0.178691  ...  0.219563  0.671909  0.357985   
...         ...       ...       ...  ...       ...       ...       ...   
19730  0.864865  0.765258  0.752031  ...  0.864724  0.729443  0.891747   
19731  0.864865  0.765258  0.754897  ...  0.864724  0.729443  0.887460   
19732  0.864865  0.771233  0.754897  ...  0.864724  0.729443  0.883173   
19733  0.864865  0.773794  0.752031  ...  0.864724  0.730581  0.878885   
19734  0.864865  0.781192  0.752031  ...  0.864724  0.731719  0.874598   

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
0         0.097674  0.894737   0.500000    0.953846   0.538462  0.265449   
1         0.100000  0.894737   0.476190    0.894872   0.533937  0.372083   
2         0.102326  0.894737   0.452381    0.835897   0.529412  0.572848   
3         0.104651  0.894737   0.428571    0.776923   0.524887  0.908261   
4         0.106977  0.894737   0.404762    0.717949   0.520362  0.201611   
...            ...       ...        ...         ...        ...       ...   
19730     0.602326  0.416667   0.238095    0.348718   0.901961  0.861981   
19731     0.602326  0.421053   0.250000    0.361538   0.900452  0.985726   
19732     0.602326  0.425439   0.261905    0.374359   0.898944  0.583979   
19733     0.602326  0.429825   0.273810    0.387179   0.897436  0.126371   
19734     0.602326  0.434211   0.285714    0.400000   0.895928  0.682391   

            rv2  
0      0.265449  
1      0.372083  
2      0.572848  
3      0.908261  
4      0.201611  
...         ...  
19730  0.861981  
19731  0.985726  
19732  0.583979  
19733  0.126371  
19734  0.682391  

[19735 rows x 27 columns]

In [17]:
y = np.array(new_data['Appliances'])

In [18]:
x = new_data.drop(columns=['Appliances'], axis=1)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                            test_size=0.3, random_state=42)

In [23]:
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
predicted_values = linear_model.predict(X_test)
predicted_values

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

In [24]:
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 2)

0.05

### What is the Residual Sum of Squares (in two decimal places)?

In [25]:
rss = np.sum(np.square(y_test - predicted_values))

In [26]:
round(rss, 2)

45.35

### What is the Root Mean Squared Error (in three decimal places)?

In [27]:
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)

0.088

### What is the Coefficient of Determination (in two decimal places)?

In [28]:
r2_score = r2_score(y_test, predicted_values)
round(r2_score, 2)

0.15

### Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

In [29]:
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(X_train, y_train)

Ridge(alpha=0.5)

In [30]:
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)

Lasso(alpha=0.001)

In [31]:
#this function returns the weight of features in the dataframe
def get_weights_df(model, data, col_name):
    weights = pd.Series(model.coef_, data.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

In [32]:
linear_model_weights = get_weights_df(linear_model, X_train, 'Linear_model')
Ridge_weight = get_weights_df(ridge_reg, X_train, 'Ridge_regression')
Lasso_weight = get_weights_df(lasso_reg, X_train, 'Lasso_regression')

In [33]:
final_df = pd.merge(linear_model_weights, Ridge_weight, on="Features")
final_df = pd.merge(final_df, Lasso_weight, on='Features')

In [34]:
final_df.sort_values(by='Linear_model')

Features  Linear_model  Ridge_regression  Lasso_regression
0          RH_2     -0.456698         -0.401134         -0.000000
1         T_out     -0.321860         -0.250765          0.000000
2            T2     -0.236178         -0.193880          0.000000
3            T9     -0.189941         -0.188584         -0.000000
4          RH_8     -0.157595         -0.156596         -0.000110
5        RH_out     -0.077671         -0.050541         -0.049557
6          RH_7     -0.044614         -0.046291         -0.000000
7          RH_9     -0.039800         -0.041701         -0.000000
8            T5     -0.015657         -0.020727         -0.000000
9            T1     -0.003281         -0.021549          0.000000
10          rv1      0.000770          0.000743         -0.000000
11          rv2      0.000770          0.000743         -0.000000
12  Press_mm_hg      0.006839          0.006516         -0.000000
13           T7      0.010319          0.010021         -0.000000
14   Visibility      0.012307          0.012032          0.000000
15         RH_5      0.016006          0.016176          0.000000
16         RH_4      0.026386          0.024168          0.000000
17           T4      0.028981          0.027006         -0.000000
18    Windspeed      0.029183          0.030463          0.002912
19         RH_6      0.038049          0.035023         -0.000000
20         RH_3      0.096048          0.094976          0.000000
21           T8      0.101995          0.100754          0.000000
22    Tdewpoint      0.117758          0.076668          0.000000
23           T6      0.236425          0.213316          0.000000
24           T3      0.290627          0.287408          0.000000
25         RH_1      0.553547          0.511932          0.017880

### Train a ridge regression model with an alpha value of 0.4. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

In [35]:
ridge_regr = Ridge(alpha=0.4)
ridge_regr.fit(X_train, y_train)

Ridge(alpha=0.4)

In [36]:
pred = ridge_regr.predict(X_test)

In [37]:
rmse_ridge = np.sqrt(mean_squared_error(y_test, pred))
round(rmse_ridge, 2)

0.09

In [38]:
print("The value of the Root mean Squared error(RMSE) on the linear model is {}".format(round(rmse, 3)))
print("The value of the Root mean Squared error(RMSE) on the Ridge Regression model is {}".format(round(rmse_ridge, 2)))

The value of the Root mean Squared error(RMSE) on the linear model is 0.088
The value of the Root mean Squared error(RMSE) on the Ridge Regression model is 0.09


> Answer: From the results above, it can be observed that there was a change in the value of the root mean squared error(RMSE) evaluated on the test set when using a RidgeRegression to train the model

### Train a lasso regression model with an alpha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights?

In [39]:
lasso_reg = Lasso(alpha=0.001)

In [40]:
lasso_reg.fit(X_train, y_train)

Lasso(alpha=0.001)

In [41]:
lasso_pred = lasso_reg.predict(X_test)
lasso_pred

array([0.07370267, 0.08143458, 0.07716072, ..., 0.07792848, 0.09034412,
       0.08359255])

In [42]:
lasso_model_weights = get_weights_df(lasso_reg, X_train, 'Lasso_Model_weight')
lasso_model_weights

Features  Lasso_Model_weight
0        RH_out           -0.049557
1          RH_8           -0.000110
2            T1            0.000000
3     Tdewpoint            0.000000
4    Visibility            0.000000
5   Press_mm_hg           -0.000000
6         T_out            0.000000
7          RH_9           -0.000000
8            T9           -0.000000
9            T8            0.000000
10         RH_7           -0.000000
11          rv1           -0.000000
12           T7           -0.000000
13           T6            0.000000
14         RH_5            0.000000
15           T5           -0.000000
16         RH_4            0.000000
17           T4           -0.000000
18         RH_3            0.000000
19           T3            0.000000
20         RH_2           -0.000000
21           T2            0.000000
22         RH_6           -0.000000
23          rv2           -0.000000
24    Windspeed            0.002912
25         RH_1            0.017880

In [43]:
def check_count_nonzero_values(df):
    counter_df = len([item for item in df if item != 0])
    return counter_df

In [44]:
print("The number of features having non_zero feature weights is {}".format(check_count_nonzero_values(lasso_model_weights)))

The number of features having non_zero feature weights is 2


### What is the new RMSE with the lasso regression? (Answer should be in three (3) decimal places)

In [45]:
lasso_rmse = np.sqrt(mean_squared_error(y_test, lasso_pred))
round(lasso_rmse, 3)

0.094